-- Seed ~40 common Costa Rica species
INSERT INTO public.species (name_es, name_en, scientific_name, habitat, description_es, description_en) VALUES
('Guapote', 'Rainbow Bass', 'Parachromis dovii', 'freshwater', 'Depredador agresivo de agua dulce, muy buscado por pescadores deportivos.', 'Aggressive freshwater predator, highly sought by sport fishermen.'),
('Machaca', 'Machaca', 'Brycon guatemalensis', 'freshwater', 'Pez herbívoro de ríos tropicales, conocido por sus saltos.', 'Herbivorous tropical river fish, known for its jumping ability.'),
('Róbalo', 'Snook', 'Centropomus undecimalis', 'brackish', 'Pez costero popular, se encuentra en estuarios y manglares.', 'Popular coastal fish found in estuaries and mangroves.'),
('Sábalo', 'Tarpon', 'Megalops atlanticus', 'saltwater', 'El rey de la pesca deportiva, famoso por sus saltos espectaculares.', 'The king of sport fishing, famous for its spectacular jumps.'),
('Pargo Rojo', 'Red Snapper', 'Lutjanus campechanus', 'saltwater', 'Pez de arrecife muy apreciado por su carne.', 'Reef fish highly valued for its meat.'),
('Pargo Manchado', 'Spotted Snapper', 'Lutjanus guttatus', 'saltwater', 'Pargo común del Pacífico con manchas características.', 'Common Pacific snapper with characteristic spots.'),
('Dorado', 'Mahi-Mahi', 'Coryphaena hippurus', 'saltwater', 'Pez pelágico colorido, excelente para pesca deportiva.', 'Colorful pelagic fish, excellent for sport fishing.'),
('Marlín Azul', 'Blue Marlin', 'Makaira nigricans', 'saltwater', 'El pez más codiciado de la pesca de altura.', 'The most coveted fish in offshore fishing.'),
('Marlín Rayado', 'Striped Marlin', 'Kajikia audax', 'saltwater', 'Marlín del Pacífico con rayas verticales.', 'Pacific marlin with vertical stripes.'),
('Pez Vela', 'Sailfish', 'Istiophorus platypterus', 'saltwater', 'El pez más rápido del océano, con su aleta dorsal característica.', 'The fastest fish in the ocean, with its characteristic dorsal fin.'),
('Wahoo', 'Wahoo', 'Acanthocybium solandri', 'saltwater', 'Pez rápido de aguas profundas con carne exquisita.', 'Fast deep-water fish with exquisite meat.'),
('Atún Aleta Amarilla', 'Yellowfin Tuna', 'Thunnus albacares', 'saltwater', 'Atún pelágico potente, popular en pesca deportiva.', 'Powerful pelagic tuna, popular in sport fishing.'),
('Corvina Aguada', 'Corvina', 'Cynoscion squamipinnis', 'saltwater', 'Pez de fondo muy apreciado en la gastronomía costarricense.', 'Bottom fish highly valued in Costa Rican cuisine.'),
('Jurel', 'Jack Crevalle', 'Caranx hippos', 'saltwater', 'Pez fuerte y agresivo, común en aguas costeras.', 'Strong and aggressive fish, common in coastal waters.'),
('Palometa', 'Permit', 'Trachinotus falcatus', 'saltwater', 'Pez de flats, desafío para pescadores con mosca.', 'Flats fish, a challenge for fly fishermen.'),
('Cubera', 'Cubera Snapper', 'Lutjanus cyanopterus', 'saltwater', 'El pargo más grande, habita arrecifes profundos.', 'The largest snapper, inhabits deep reefs.'),
('Sierra', 'Spanish Mackerel', 'Scomberomorus maculatus', 'saltwater', 'Pez pelágico rápido con manchas oscuras.', 'Fast pelagic fish with dark spots.'),
('Barracuda', 'Barracuda', 'Sphyraena barracuda', 'saltwater', 'Depredador con dientes afilados, común en arrecifes.', 'Predator with sharp teeth, common in reefs.'),
('Mero', 'Grouper', 'Epinephelus quinquefasciatus', 'saltwater', 'Pez de arrecife grande y fuerte, excelente para comer.', 'Large and strong reef fish, excellent for eating.'),
('Tiburón Toro', 'Bull Shark', 'Carcharhinus leucas', 'brackish', 'Tiburón que se adentra en ríos y aguas salobres.', 'Shark that enters rivers and brackish waters.'),
('Mojarra', 'Mojarra', 'Gerres cinereus', 'brackish', 'Pez pequeño común en estuarios y costas.', 'Small fish common in estuaries and coasts.'),
('Bobo', 'Mountain Mullet', 'Joturus pichardi', 'freshwater', 'Pez de montaña que habita ríos con corriente rápida.', 'Mountain fish that inhabits fast-flowing rivers.'),
('Tilapia', 'Tilapia', 'Oreochromis niloticus', 'freshwater', 'Pez introducido muy común en lagos y embalses.', 'Commonly introduced fish in lakes and reservoirs.'),
('Barbudo', 'Catfish', 'Rhamdia guatemalensis', 'freshwater', 'Pez de fondo nocturno, habita ríos y lagos.', 'Nocturnal bottom fish, inhabits rivers and lakes.'),
('Tepemechín', 'River Mullet', 'Agonostomus monticola', 'freshwater', 'Lisa de río que migra entre agua dulce y salada.', 'River mullet that migrates between fresh and salt water.'),
('Vieja', 'Mayan Cichlid', 'Mayaheros urophthalmus', 'freshwater', 'Cíclido colorido de lagos y lagunas.', 'Colorful cichlid from lakes and lagoons.'),
('Gaspar', 'Tropical Gar', 'Atractosteus tropicus', 'freshwater', 'Pez primitivo con escamas duras, habita aguas lentas.', 'Primitive fish with hard scales, inhabits slow waters.'),
('Roncador', 'Grunt', 'Haemulon plumierii', 'saltwater', 'Pez de arrecife que produce sonidos con sus dientes.', 'Reef fish that produces sounds with its teeth.'),
('Pez Gallo', 'Roosterfish', 'Nematistius pectoralis', 'saltwater', 'Pez trofeo del Pacífico con cresta dorsal impresionante.', 'Pacific trophy fish with impressive dorsal crest.'),
('Lisa', 'Mullet', 'Mugil cephalus', 'brackish', 'Pez costero común, se alimenta de algas y detritos.', 'Common coastal fish, feeds on algae and detritus.'),
('Pez Aguja', 'Needlefish', 'Strongylura notata', 'saltwater', 'Pez alargado con mandíbulas puntiagudas.', 'Elongated fish with pointed jaws.'),
('Cojinuda', 'Blue Runner', 'Caranx crysos', 'saltwater', 'Jurel pequeño y rápido, común en cardúmenes costeros.', 'Small, fast jack, common in coastal schools.'),
('Pez Espada', 'Swordfish', 'Xiphias gladius', 'saltwater', 'Gran pez pelágico con mandíbula superior alargada.', 'Large pelagic fish with elongated upper jaw.'),
('Cobia', 'Cobia', 'Rachycentron canadum', 'saltwater', 'Pez pelágico solitario con carne excelente.', 'Solitary pelagic fish with excellent meat.'),
('Pampano', 'Pompano', 'Trachinotus carolinus', 'saltwater', 'Pez plateado de costas, muy apreciado por su sabor.', 'Silver coastal fish, highly valued for its flavor.'),
('Cabrilla', 'Cabrilla Sea Bass', 'Epinephelus labriformis', 'saltwater', 'Pez de arrecife del Pacífico con puntos rojos.', 'Pacific reef fish with red spots.'),
('Raya', 'Stingray', 'Dasyatis americana', 'saltwater', 'Pez plano con aguijón venenoso en la cola.', 'Flat fish with a venomous stinger on its tail.'),
('Sardina', 'Sardine', 'Sardinella aurita', 'saltwater', 'Pez forrajero pequeño, usado como carnada y alimento.', 'Small bait fish, used as bait and food.'),
('Trucha Arcoíris', 'Rainbow Trout', 'Oncorhynchus mykiss', 'freshwater', 'Trucha introducida en ríos de montaña de Costa Rica.', 'Trout introduced to Costa Rica''s mountain rivers.'),
('Olomina', 'Livebearing Fish', 'Poecilia gillii', 'freshwater', 'Pez pequeño abundante en ríos y arroyos.', 'Small fish abundant in rivers and streams.');
