-- Seed fishing data for all species (keyed by scientific_name)

UPDATE public.species SET max_weight_kg = 6.8, max_length_cm = 72, fishing_regions_es = 'Lago Arenal, Río Tempisque, Río Bebedero, Caño Negro, Río Frío, Lago Cachí', fishing_regions_en = 'Lake Arenal, Tempisque River, Bebedero River, Caño Negro, Frío River, Cachí Reservoir', best_bait_es = 'Señuelos de superficie (poppers), crankbaits medianos, peces vivos pequeños', best_bait_en = 'Topwater poppers, medium crankbaits, small live baitfish' WHERE scientific_name = 'Parachromis dovii';

UPDATE public.species SET max_weight_kg = 4.3, max_length_cm = 59, fishing_regions_es = 'Río Sarapiquí, Río Reventazón, Río Pacuare, Río San Juan, Río Tortuguero', fishing_regions_en = 'Sarapiquí River, Reventazón River, Pacuare River, San Juan River, Tortuguero River', best_bait_es = 'Frutas (mango, guayaba), señuelos de cuchara, gusanos', best_bait_en = 'Fruits (mango, guava), spoon lures, worms' WHERE scientific_name = 'Brycon guatemalensis';

UPDATE public.species SET max_weight_kg = 24.3, max_length_cm = 140, fishing_regions_es = 'Barra del Colorado, Tortuguero, Río Parismina, Costa Caribe, Río Sierpe', fishing_regions_en = 'Barra del Colorado, Tortuguero, Parismina River, Caribbean Coast, Sierpe River', best_bait_es = 'Mulitas vivas, camarones, señuelos de natación (swimbaits)', best_bait_en = 'Live mullet, shrimp, swimbaits' WHERE scientific_name = 'Centropomus undecimalis';

UPDATE public.species SET max_weight_kg = 161.0, max_length_cm = 250, fishing_regions_es = 'Barra del Colorado, Tortuguero, Río Parismina, Laguna de Barra del Colorado, Costa Caribe', fishing_regions_en = 'Barra del Colorado, Tortuguero, Parismina River, Barra del Colorado Lagoon, Caribbean Coast', best_bait_es = 'Mulitas vivas, sardinas, señuelos articulados grandes', best_bait_en = 'Live mullet, sardines, large jointed lures' WHERE scientific_name = 'Megalops atlanticus';

UPDATE public.species SET max_weight_kg = 22.8, max_length_cm = 100, fishing_regions_es = 'Golfo de Papagayo, Quepos, Golfo Dulce, Costa Pacífica Norte', fishing_regions_en = 'Papagayo Gulf, Quepos, Golfo Dulce, Northern Pacific Coast', best_bait_es = 'Camarones, calamares, peces de fondo vivos', best_bait_en = 'Shrimp, squid, live bottom fish' WHERE scientific_name = 'Lutjanus campechanus';

UPDATE public.species SET max_weight_kg = 6.0, max_length_cm = 80, fishing_regions_es = 'Quepos, Jacó, Golfo Dulce, Golfo de Nicoya, Puntarenas, Guanacaste', fishing_regions_en = 'Quepos, Jacó, Golfo Dulce, Gulf of Nicoya, Puntarenas, Guanacaste', best_bait_es = 'Camarones, calamares, señuelos de fondo', best_bait_en = 'Shrimp, squid, bottom jigs' WHERE scientific_name = 'Lutjanus guttatus';

UPDATE public.species SET max_weight_kg = 40.0, max_length_cm = 210, fishing_regions_es = 'Quepos, Los Sueños, Jacó, Golfo de Papagayo, Golfito, Pacífico Central y Sur', fishing_regions_en = 'Quepos, Los Sueños, Jacó, Papagayo Gulf, Golfito, Central and South Pacific', best_bait_es = 'Señuelos planeadores (chuggers), peces voladores, calamares', best_bait_en = 'Trolling chugger lures, flying fish, squid' WHERE scientific_name = 'Coryphaena hippurus';

UPDATE public.species SET max_weight_kg = 636.0, max_length_cm = 500, fishing_regions_es = 'Quepos, Los Sueños, Papagayo, Golfito, Golfo Dulce, Pacífico Costarricense', fishing_regions_en = 'Quepos, Los Sueños, Papagayo, Golfito, Golfo Dulce, Costa Rican Pacific', best_bait_es = 'Carnadas vivas (bonito, dorado), señuelos de trolling grandes', best_bait_en = 'Live bait (bonito, mahi-mahi), large trolling lures' WHERE scientific_name = 'Makaira nigricans';

UPDATE public.species SET max_weight_kg = 440.0, max_length_cm = 420, fishing_regions_es = 'Quepos, Los Sueños, Papagayo, Pacífico Norte y Central', fishing_regions_en = 'Quepos, Los Sueños, Papagayo, Northern and Central Pacific', best_bait_es = 'Señuelos de trolling, calamares, carnadas vivas', best_bait_en = 'Trolling lures, squid, live bait' WHERE scientific_name = 'Kajikia audax';

UPDATE public.species SET max_weight_kg = 100.2, max_length_cm = 348, fishing_regions_es = 'Quepos, Los Sueños, Golfo de Papagayo, Guanacaste, Jacó, Golfito', fishing_regions_en = 'Quepos, Los Sueños, Papagayo Gulf, Guanacaste, Jacó, Golfito', best_bait_es = 'Señuelos de trolling, plumas, sardinas vivas o ballyhoo', best_bait_en = 'Trolling lures, feathers, live sardines or ballyhoo' WHERE scientific_name = 'Istiophorus platypterus';

UPDATE public.species SET max_weight_kg = 83.0, max_length_cm = 250, fishing_regions_es = 'Quepos, Los Sueños, Papagayo, Golfo Dulce, aguas offshore del Pacífico', fishing_regions_en = 'Quepos, Los Sueños, Papagayo, Golfo Dulce, Pacific offshore waters', best_bait_es = 'Señuelos de trolling de alta velocidad, calamares, peces vivos', best_bait_en = 'High-speed trolling lures, squid, live bait' WHERE scientific_name = 'Acanthocybium solandri';

UPDATE public.species SET max_weight_kg = 200.0, max_length_cm = 239, fishing_regions_es = 'Quepos, Los Sueños, Papagayo, aguas offshore del Pacífico, Golfito', fishing_regions_en = 'Quepos, Los Sueños, Papagayo, Pacific offshore waters, Golfito', best_bait_es = 'Sardinas vivas, anchovetas, señuelos de pluma, popping', best_bait_en = 'Live sardines, anchovies, feather lures, popping' WHERE scientific_name = 'Thunnus albacares';

UPDATE public.species SET max_weight_kg = 2.5, max_length_cm = 64, fishing_regions_es = 'Golfo de Nicoya, Puntarenas, Quepos, estuarios del Pacífico', fishing_regions_en = 'Gulf of Nicoya, Puntarenas, Quepos, Pacific estuaries', best_bait_es = 'Camarones, sardinas, señuelos de vinil (grubs)', best_bait_en = 'Shrimp, sardines, soft plastic grubs' WHERE scientific_name = 'Cynoscion squamipinnis';

UPDATE public.species SET max_weight_kg = 32.0, max_length_cm = 124, fishing_regions_es = 'Barra del Colorado, Tortuguero, Quepos, Golfo de Nicoya, Costa Caribe y Pacífica', fishing_regions_en = 'Barra del Colorado, Tortuguero, Quepos, Gulf of Nicoya, Caribbean and Pacific coasts', best_bait_es = 'Señuelos metálicos (jigs), sardinas vivas, poppers de superficie', best_bait_en = 'Metal jigs, live sardines, topwater poppers' WHERE scientific_name = 'Caranx hippos';

UPDATE public.species SET max_weight_kg = 36.0, max_length_cm = 122, fishing_regions_es = 'Costa Caribe, playas arenosas del Caribe costarricense, Limón', fishing_regions_en = 'Caribbean Coast, sandy Caribbean beaches of Costa Rica, Limón', best_bait_es = 'Cangrejos de arena, camarones, señuelos de plomo (jigs)', best_bait_en = 'Sand crabs, shrimp, lead jigs' WHERE scientific_name = 'Trachinotus falcatus';

UPDATE public.species SET max_weight_kg = 57.0, max_length_cm = 160, fishing_regions_es = 'Barra del Colorado, Tortuguero, Río Parismina, arrecifes del Caribe costarricense', fishing_regions_en = 'Barra del Colorado, Tortuguero, Parismina River, Costa Rican Caribbean reefs', best_bait_es = 'Peces vivos, calamares, carnadas de fondo', best_bait_en = 'Live fish, squid, bottom baits' WHERE scientific_name = 'Lutjanus cyanopterus';

UPDATE public.species SET max_weight_kg = 5.9, max_length_cm = 91, fishing_regions_es = 'Costa Caribe, Limón, Bocas del Dragón, aguas costeras del Atlántico', fishing_regions_en = 'Caribbean Coast, Limón, Bocas del Dragón, Atlantic coastal waters', best_bait_es = 'Señuelos de trolling plateados, sardinas, señuelos de cuchara', best_bait_en = 'Silver trolling lures, sardines, spoon lures' WHERE scientific_name = 'Scomberomorus maculatus';

UPDATE public.species SET max_weight_kg = 50.0, max_length_cm = 200, fishing_regions_es = 'Quepos, Golfo de Nicoya, Costa Caribe, Barra del Colorado, arrecifes costeros', fishing_regions_en = 'Quepos, Gulf of Nicoya, Caribbean Coast, Barra del Colorado, coastal reefs', best_bait_es = 'Señuelos largos plateados, peces vivos, señuelos de natación', best_bait_en = 'Long silver lures, live fish, swimbaits' WHERE scientific_name = 'Sphyraena barracuda';

UPDATE public.species SET max_weight_kg = 25.0, max_length_cm = 100, fishing_regions_es = 'Golfo Dulce, Quepos, Isla del Coco, Golfo de Nicoya, fondos rocosos del Pacífico', fishing_regions_en = 'Golfo Dulce, Quepos, Cocos Island, Gulf of Nicoya, Pacific rocky bottoms', best_bait_es = 'Peces vivos, calamares, carnadas de fondo', best_bait_en = 'Live fish, squid, bottom baits' WHERE scientific_name = 'Epinephelus quinquefasciatus';

UPDATE public.species SET max_weight_kg = 316.5, max_length_cm = 400, fishing_regions_es = 'Río San Juan, Barra del Colorado, desembocaduras de ríos del Caribe, Golfo de Nicoya', fishing_regions_en = 'San Juan River, Barra del Colorado, Caribbean river mouths, Gulf of Nicoya', best_bait_es = 'Carnadas enteras (peces, rayas), anzuelos de fondo grandes', best_bait_en = 'Whole fish bait (fish, stingray chunks), large bottom rigs' WHERE scientific_name = 'Carcharhinus leucas';

UPDATE public.species SET max_weight_kg = 0.53, max_length_cm = 41, fishing_regions_es = 'Estuarios del Caribe, Golfo de Nicoya, manglares de Puntarenas, playas del Pacífico', fishing_regions_en = 'Caribbean estuaries, Gulf of Nicoya, Puntarenas mangroves, Pacific beaches', best_bait_es = 'Gusanos de arena, camarones pequeños, masa de pan', best_bait_en = 'Sand worms, small shrimp, bread dough' WHERE scientific_name = 'Gerres cinereus';

UPDATE public.species SET max_weight_kg = 3.3, max_length_cm = 61, fishing_regions_es = 'Río Sarapiquí, Río San Juan, Río Pacuare, ríos de la vertiente Caribe', fishing_regions_en = 'Sarapiquí River, San Juan River, Pacuare River, Caribbean slope rivers', best_bait_es = 'Frutas maduras (higo, mango), algas, masa', best_bait_en = 'Ripe fruits (fig, mango), algae, dough' WHERE scientific_name = 'Joturus pichardi';

UPDATE public.species SET max_weight_kg = 4.3, max_length_cm = 60, fishing_regions_es = 'Lago Arenal, Lago Cachí, Río Tempisque, embalses y estanques en todo el país', fishing_regions_en = 'Lake Arenal, Cachí Reservoir, Tempisque River, reservoirs and ponds throughout the country', best_bait_es = 'Gusanos, masa de maíz, señuelos pequeños de vinil', best_bait_en = 'Worms, corn dough, small soft plastic lures' WHERE scientific_name = 'Oreochromis niloticus';

UPDATE public.species SET max_weight_kg = 0.30, max_length_cm = 25, fishing_regions_es = 'Ríos de la vertiente Caribe, Río Reventazón, Río Sarapiquí, cuerpos de agua lentos', fishing_regions_en = 'Caribbean slope rivers, Reventazón River, Sarapiquí River, slow-moving water bodies', best_bait_es = 'Gusanos, trozos de carne, camarones de río', best_bait_en = 'Worms, meat pieces, freshwater shrimp' WHERE scientific_name = 'Rhamdia guatemalensis';

UPDATE public.species SET max_weight_kg = 0.42, max_length_cm = 36, fishing_regions_es = 'Ríos de montaña del Caribe, Río Pacuare, Río Reventazón, Río Sarapiquí', fishing_regions_en = 'Caribbean mountain rivers, Pacuare River, Reventazón River, Sarapiquí River', best_bait_es = 'Algas, masa, gusanos pequeños', best_bait_en = 'Algae, dough, small worms' WHERE scientific_name = 'Agonostomus monticola';

UPDATE public.species SET max_weight_kg = 1.1, max_length_cm = 39, fishing_regions_es = 'Caño Negro, Río Frío, Río San Juan, lagunas del norte de Costa Rica', fishing_regions_en = 'Caño Negro, Frío River, San Juan River, northern Costa Rica lagoons', best_bait_es = 'Señuelos pequeños de vinil, gusanos, crankbaits pequeños', best_bait_en = 'Small soft plastic lures, worms, small crankbaits' WHERE scientific_name = 'Mayaheros urophthalmus';

UPDATE public.species SET max_weight_kg = 2.9, max_length_cm = 125, fishing_regions_es = 'Caño Negro, Río Frío, Río San Juan, lagunas del norte de Costa Rica (Guatuso, Los Chiles)', fishing_regions_en = 'Caño Negro, Frío River, San Juan River, northern Costa Rica lagoons (Guatuso, Los Chiles)', best_bait_es = 'Peces vivos, señuelos de natación, ranas artificiales', best_bait_en = 'Live fish, swimbaits, frog lures' WHERE scientific_name = 'Atractosteus tropicus';

UPDATE public.species SET max_weight_kg = 4.4, max_length_cm = 53, fishing_regions_es = 'Costa Caribe, Limón, arrecifes de Puerto Viejo, Golfo de Nicoya', fishing_regions_en = 'Caribbean Coast, Limón, Puerto Viejo reefs, Gulf of Nicoya', best_bait_es = 'Camarones, calamares, gusanos de mar', best_bait_en = 'Shrimp, squid, marine worms' WHERE scientific_name = 'Haemulon plumierii';

UPDATE public.species SET max_weight_kg = 51.7, max_length_cm = 163, fishing_regions_es = 'Playa Carrillo, Tamarindo, Flamingo, Quepos, Jacó, playas del Pacífico Norte y Central', fishing_regions_en = 'Playa Carrillo, Tamarindo, Flamingo, Quepos, Jacó, Northern and Central Pacific beaches', best_bait_es = 'Lisa viva, sardinas vivas, señuelos de superficie (poppers)', best_bait_en = 'Live mullet, live sardines, topwater poppers' WHERE scientific_name = 'Nematistius pectoralis';

UPDATE public.species SET max_weight_kg = 8.0, max_length_cm = 100, fishing_regions_es = 'Golfo de Nicoya, Puntarenas, estuarios del Pacífico, Río Tempisque, Costa Caribe', fishing_regions_en = 'Gulf of Nicoya, Puntarenas, Pacific estuaries, Tempisque River, Caribbean Coast', best_bait_es = 'Masa, algas, atarraya (captura para carnada)', best_bait_en = 'Dough, algae, cast net (captured for use as bait)' WHERE scientific_name = 'Mugil cephalus';

UPDATE public.species SET max_weight_kg = 0.15, max_length_cm = 61, fishing_regions_es = 'Costa Caribe, lagunas de Tortuguero, canales del Caribe, estuarios costeros', fishing_regions_en = 'Caribbean Coast, Tortuguero lagoons, Caribbean canals, coastal estuaries', best_bait_es = 'Señuelos pequeños plateados, trozos de pescado, cuchara pequeña', best_bait_en = 'Small silver lures, fish strips, small spoons' WHERE scientific_name = 'Strongylura notata';

UPDATE public.species SET max_weight_kg = 5.1, max_length_cm = 70, fishing_regions_es = 'Costa Caribe, Limón, arrecifes costeros del Atlántico, Bocas del Dragón', fishing_regions_en = 'Caribbean Coast, Limón, Atlantic coastal reefs, Bocas del Dragón', best_bait_es = 'Señuelos metálicos (jigs), sardinas, señuelos de cuchara', best_bait_en = 'Metal jigs, sardines, spoon lures' WHERE scientific_name = 'Caranx crysos';

UPDATE public.species SET max_weight_kg = 650.0, max_length_cm = 455, fishing_regions_es = 'Aguas offshore del Pacífico (Quepos, Los Sueños), zonas de aguas profundas frente a Guanacaste', fishing_regions_en = 'Pacific offshore waters (Quepos, Los Sueños), deep-water zones off Guanacaste', best_bait_es = 'Calamares, peces vivos a profundidad, señuelos de pesca nocturna', best_bait_en = 'Squid, deep live bait, nighttime fishing lures' WHERE scientific_name = 'Xiphias gladius';

UPDATE public.species SET max_weight_kg = 68.0, max_length_cm = 200, fishing_regions_es = 'Golfo de Nicoya, Puntarenas, Quepos, Costa Caribe, Barra del Colorado', fishing_regions_en = 'Gulf of Nicoya, Puntarenas, Quepos, Caribbean Coast, Barra del Colorado', best_bait_es = 'Peces vivos, calamares, señuelos de natación grandes', best_bait_en = 'Live fish, squid, large swimbaits' WHERE scientific_name = 'Rachycentron canadum';

UPDATE public.species SET max_weight_kg = 3.8, max_length_cm = 64, fishing_regions_es = 'Playas arenosas del Pacífico, Jacó, Quepos, Manuel Antonio, Guanacaste', fishing_regions_en = 'Pacific sandy beaches, Jacó, Quepos, Manuel Antonio, Guanacaste', best_bait_es = 'Cangrejos mole, camarones, señuelos jig pequeños', best_bait_en = 'Mole crabs, shrimp, small jig lures' WHERE scientific_name = 'Trachinotus carolinus';

UPDATE public.species SET max_weight_kg = 3.5, max_length_cm = 60, fishing_regions_es = 'Golfo Dulce, Isla del Coco, arrecifes rocosos del Pacífico Norte y Central, Guanacaste', fishing_regions_en = 'Golfo Dulce, Cocos Island, rocky reefs of Northern and Central Pacific, Guanacaste', best_bait_es = 'Camarones, trozos de calamar, carnadas de fondo', best_bait_en = 'Shrimp, squid strips, bottom baits' WHERE scientific_name = 'Epinephelus labriformis';

UPDATE public.species SET max_weight_kg = 135.6, max_length_cm = 200, fishing_regions_es = 'Fondos arenosos del Caribe, Golfo de Nicoya, Puntarenas, Tortuguero', fishing_regions_en = 'Caribbean sandy bottoms, Gulf of Nicoya, Puntarenas, Tortuguero', best_bait_es = 'Calamares, camarones, trozos de pescado en fondo', best_bait_en = 'Squid, shrimp, fish chunks on bottom' WHERE scientific_name = 'Dasyatis americana';

UPDATE public.species SET max_weight_kg = 0.42, max_length_cm = 41, fishing_regions_es = 'Costa Caribe, Limón, aguas costeras del Atlántico, Golfo de Nicoya', fishing_regions_en = 'Caribbean Coast, Limón, Atlantic coastal waters, Gulf of Nicoya', best_bait_es = 'Redes de atarraya, anzuelos pequeños con masa, carnada viva para otras especies', best_bait_en = 'Cast nets, small hooks with dough, live bait for other species' WHERE scientific_name = 'Sardinella aurita';

UPDATE public.species SET max_weight_kg = 25.9, max_length_cm = 122, fishing_regions_es = 'Volcán Poás (alto Río Sarapiquí), Volcán Barva, Talamanca, ríos de altura de Cartago', fishing_regions_en = 'Poás Volcano (upper Sarapiquí River), Barva Volcano, Talamanca, Cartago highland rivers', best_bait_es = 'Moscas artificiales, gusanos, señuelos tipo spinner', best_bait_en = 'Artificial flies, worms, spinner lures' WHERE scientific_name = 'Oncorhynchus mykiss';

UPDATE public.species SET max_weight_kg = 0.01, max_length_cm = 10, fishing_regions_es = 'Ríos y quebradas de baja altitud en todo Costa Rica, vertiente Caribe y Pacífica', fishing_regions_en = 'Low-altitude rivers and streams throughout Costa Rica, Caribbean and Pacific slopes', best_bait_es = 'Anzuelos muy pequeños con masa, gusanos diminutos (pesca artesanal)', best_bait_en = 'Very small hooks with dough, tiny worms (artisanal fishing)' WHERE scientific_name = 'Poecilia gillii';
